name: Go Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Verify gofmt
        run: |
          GOFMT_OUTPUT=$(gofmt -l .)
          if [ -n "$GOFMT_OUTPUT" ]; then
            echo "The following files are not formatted with gofmt:"
            echo "$GOFMT_OUTPUT"
            echo "Please run 'gofmt -w .' to format your code."
            exit 1
          fi
          echo "✅ All Go files are properly formatted with gofmt."

      - name: Run golint
        run: |
          GOLINT_OUTPUT=$(golint ./...)
          if [ -n "$GOLINT_OUTPUT" ]; then
            echo "golint found issues:"
            echo "$GOLINT_OUTPUT"
            exit 1
          fi
          echo "✅ No linting issues found with golint."

      - name: Run tests
        run: go test -v ./...
